//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoncharovFitnesClub.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscription
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Subscription()
        {
            this.Client = new HashSet<Client>();
        }
    
        public int SubscriptionID { get; set; }
        public string NameSubscription { get; set; }
        public Nullable<int> SpecialityID { get; set; }
        public Nullable<int> CoachID { get; set; }
        public int AmountOfDays { get; set; }
        public Nullable<int> VisitDateID { get; set; }
        public string TimeOfVisit { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Client> Client { get; set; }
        public virtual Coach Coach { get; set; }
        public virtual Speciality Speciality { get; set; }
        public virtual VisitDate VisitDate { get; set; }
    }
}
